// Auto-generated by prost-build. DO NOT EDIT MANUALLY.
//
// Source of truth: crates/raidian/proto/*.proto
// Regenerate with: bash crates/raidian/generate.sh
//
// This file is intentionally committed so that downstream consumers
// (CLI, Zed, Logos, etc.) do not need `protoc` installed.

// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PeerId {
    #[prost(uint32, tag = "1")]
    pub owner_id: u32,
    #[prost(uint32, tag = "2")]
    pub id: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hello {
    #[prost(message, optional, tag = "1")]
    pub peer_id: ::core::option::Option<PeerId>,
    #[prost(string, tag = "2")]
    pub protocol_version: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ack {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "error::Code", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub tags: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Nested message and enum types in `Error`.
pub mod error {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Code {
        Unknown = 0,
        Disconnected = 1,
        UpgradeRequired = 2,
        Internal = 3,
        PermissionDenied = 4,
        NotFound = 5,
        RateLimited = 6,
        WrongReleaseChannel = 7,
    }
    impl Code {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::Disconnected => "DISCONNECTED",
                Self::UpgradeRequired => "UPGRADE_REQUIRED",
                Self::Internal => "INTERNAL",
                Self::PermissionDenied => "PERMISSION_DENIED",
                Self::NotFound => "NOT_FOUND",
                Self::RateLimited => "RATE_LIMITED",
                Self::WrongReleaseChannel => "WRONG_RELEASE_CHANNEL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "DISCONNECTED" => Some(Self::Disconnected),
                "UPGRADE_REQUIRED" => Some(Self::UpgradeRequired),
                "INTERNAL" => Some(Self::Internal),
                "PERMISSION_DENIED" => Some(Self::PermissionDenied),
                "NOT_FOUND" => Some(Self::NotFound),
                "RATE_LIMITED" => Some(Self::RateLimited),
                "WRONG_RELEASE_CHANNEL" => Some(Self::WrongReleaseChannel),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ping {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Pong {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Room {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(message, repeated, tag = "2")]
    pub participants: ::prost::alloc::vec::Vec<Participant>,
    #[prost(message, repeated, tag = "3")]
    pub pending_participants: ::prost::alloc::vec::Vec<PendingParticipant>,
    #[prost(message, repeated, tag = "4")]
    pub shared_projects: ::prost::alloc::vec::Vec<ParticipantProject>,
    #[prost(string, tag = "5")]
    pub live_kit_room: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "6")]
    pub channel_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Participant {
    #[prost(uint64, tag = "1")]
    pub user_id: u64,
    #[prost(message, optional, tag = "2")]
    pub peer_id: ::core::option::Option<PeerId>,
    #[prost(message, repeated, tag = "3")]
    pub projects: ::prost::alloc::vec::Vec<ParticipantProject>,
    #[prost(message, optional, tag = "4")]
    pub location: ::core::option::Option<ParticipantLocation>,
    #[prost(uint32, tag = "5")]
    pub participant_index: u32,
    #[prost(enumeration = "ParticipantRole", tag = "6")]
    pub role: i32,
    #[prost(string, optional, tag = "7")]
    pub muted_reason: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PendingParticipant {
    #[prost(uint64, tag = "1")]
    pub user_id: u64,
    #[prost(uint64, tag = "2")]
    pub calling_user_id: u64,
    #[prost(uint64, optional, tag = "3")]
    pub initial_project_id: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantProject {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, repeated, tag = "2")]
    pub worktree_root_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ParticipantLocation {
    #[prost(oneof = "participant_location::Variant", tags = "1, 2, 3")]
    pub variant: ::core::option::Option<participant_location::Variant>,
}
/// Nested message and enum types in `ParticipantLocation`.
pub mod participant_location {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct SharedProject {
        #[prost(uint64, tag = "1")]
        pub id: u64,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct UnsharedProject {}
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct External {}
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Variant {
        #[prost(message, tag = "1")]
        SharedProject(SharedProject),
        #[prost(message, tag = "2")]
        UnsharedProject(UnsharedProject),
        #[prost(message, tag = "3")]
        External(External),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreateRoom {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateRoomResponse {
    #[prost(message, optional, tag = "1")]
    pub room: ::core::option::Option<Room>,
    #[prost(string, tag = "2")]
    pub live_kit_connection_info_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub live_kit_connection_info_server_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JoinRoom {
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinRoomResponse {
    #[prost(message, optional, tag = "1")]
    pub room: ::core::option::Option<Room>,
    #[prost(string, tag = "2")]
    pub live_kit_connection_info_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub live_kit_connection_info_server_url: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "4")]
    pub channel_id: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveRoom {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomUpdated {
    #[prost(message, optional, tag = "1")]
    pub room: ::core::option::Option<Room>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(uint64, tag = "2")]
    pub called_user_id: u64,
    #[prost(uint64, optional, tag = "3")]
    pub initial_project_id: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IncomingCall {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(uint64, tag = "2")]
    pub calling_user_id: u64,
    #[prost(uint64, repeated, tag = "3")]
    pub participant_user_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, optional, tag = "4")]
    pub initial_project: ::core::option::Option<ParticipantProject>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeclineCall {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ParticipantRole {
    ParticipantMember = 0,
    ParticipantAdmin = 1,
    ParticipantGuest = 2,
    ParticipantTalker = 3,
}
impl ParticipantRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ParticipantMember => "PARTICIPANT_MEMBER",
            Self::ParticipantAdmin => "PARTICIPANT_ADMIN",
            Self::ParticipantGuest => "PARTICIPANT_GUEST",
            Self::ParticipantTalker => "PARTICIPANT_TALKER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARTICIPANT_MEMBER" => Some(Self::ParticipantMember),
            "PARTICIPANT_ADMIN" => Some(Self::ParticipantAdmin),
            "PARTICIPANT_GUEST" => Some(Self::ParticipantGuest),
            "PARTICIPANT_TALKER" => Some(Self::ParticipantTalker),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWorktree {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub worktree_id: u64,
    #[prost(string, tag = "3")]
    pub root_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub abs_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub updated_entries: ::prost::alloc::vec::Vec<Entry>,
    #[prost(uint64, repeated, tag = "6")]
    pub removed_entries: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "7")]
    pub removed_repositories: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, tag = "8")]
    pub scan_id: u64,
    #[prost(bool, tag = "9")]
    pub is_last_update: bool,
    #[prost(uint64, repeated, tag = "10")]
    pub updated_repositories: ::prost::alloc::vec::Vec<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entry {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bool, tag = "2")]
    pub is_dir: bool,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub inode: u64,
    #[prost(uint64, tag = "5")]
    pub mtime_seconds: u64,
    #[prost(uint32, tag = "6")]
    pub mtime_nanos: u32,
    #[prost(bool, tag = "7")]
    pub is_symlink: bool,
    #[prost(bool, tag = "8")]
    pub is_external: bool,
    #[prost(bool, tag = "9")]
    pub is_ignored: bool,
    #[prost(bool, tag = "10")]
    pub is_private: bool,
    #[prost(string, optional, tag = "11")]
    pub char_bag: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "12")]
    pub git_status: ::core::option::Option<GitEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GitEntry {
    #[prost(enumeration = "git_entry::Status", tag = "1")]
    pub status: i32,
}
/// Nested message and enum types in `GitEntry`.
pub mod git_entry {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unmodified = 0,
        Modified = 1,
        Added = 2,
        Deleted = 3,
        Renamed = 4,
        Copied = 5,
        Untracked = 6,
        Ignored = 7,
        Conflicted = 8,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unmodified => "UNMODIFIED",
                Self::Modified => "MODIFIED",
                Self::Added => "ADDED",
                Self::Deleted => "DELETED",
                Self::Renamed => "RENAMED",
                Self::Copied => "COPIED",
                Self::Untracked => "UNTRACKED",
                Self::Ignored => "IGNORED",
                Self::Conflicted => "CONFLICTED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNMODIFIED" => Some(Self::Unmodified),
                "MODIFIED" => Some(Self::Modified),
                "ADDED" => Some(Self::Added),
                "DELETED" => Some(Self::Deleted),
                "RENAMED" => Some(Self::Renamed),
                "COPIED" => Some(Self::Copied),
                "UNTRACKED" => Some(Self::Untracked),
                "IGNORED" => Some(Self::Ignored),
                "CONFLICTED" => Some(Self::Conflicted),
                _ => None,
            }
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProjectEntry {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub worktree_id: u64,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_directory: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameProjectEntry {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub entry_id: u64,
    #[prost(string, tag = "3")]
    pub new_path: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteProjectEntry {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub entry_id: u64,
    #[prost(bool, tag = "3")]
    pub use_trash: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CopyProjectEntry {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub entry_id: u64,
    #[prost(string, tag = "3")]
    pub new_path: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProjectEntryResponse {
    #[prost(message, optional, tag = "1")]
    pub entry: ::core::option::Option<Entry>,
    #[prost(uint64, tag = "2")]
    pub worktree_scan_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExpandProjectEntry {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub entry_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShareProject {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub worktrees: ::prost::alloc::vec::Vec<WorktreeMetadata>,
    #[prost(bool, tag = "3")]
    pub is_ssh_project: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ShareProjectResponse {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnshareProject {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinProject {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(string, repeated, tag = "2")]
    pub committer_capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinProjectResponse {
    #[prost(uint32, tag = "1")]
    pub replica_id: u32,
    #[prost(message, repeated, tag = "2")]
    pub worktrees: ::prost::alloc::vec::Vec<WorktreeMetadata>,
    #[prost(message, repeated, tag = "3")]
    pub collaborators: ::prost::alloc::vec::Vec<Collaborator>,
    #[prost(message, repeated, tag = "4")]
    pub language_servers: ::prost::alloc::vec::Vec<LanguageServer>,
    #[prost(message, repeated, tag = "5")]
    pub repositories: ::prost::alloc::vec::Vec<RepositoryEntry>,
    #[prost(enumeration = "RoleType", tag = "6")]
    pub role: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveProject {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Collaborator {
    #[prost(message, optional, tag = "1")]
    pub peer_id: ::core::option::Option<PeerId>,
    #[prost(uint32, tag = "2")]
    pub replica_id: u32,
    #[prost(uint64, tag = "3")]
    pub user_id: u64,
    #[prost(bool, tag = "4")]
    pub is_host: bool,
    #[prost(string, optional, tag = "5")]
    pub committer_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub committer_email: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddProjectCollaborator {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, optional, tag = "2")]
    pub collaborator: ::core::option::Option<Collaborator>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveProjectCollaborator {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, optional, tag = "2")]
    pub peer_id: ::core::option::Option<PeerId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProject {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub worktrees: ::prost::alloc::vec::Vec<WorktreeMetadata>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorktreeMetadata {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub root_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub visible: bool,
    #[prost(string, tag = "4")]
    pub abs_path: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LanguageServer {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag = "3")]
    pub worktree_id: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RepositoryEntry {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(string, tag = "2")]
    pub abs_path: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RoleType {
    RoleMember = 0,
    RoleGuest = 1,
    RoleAdmin = 2,
}
impl RoleType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::RoleMember => "ROLE_MEMBER",
            Self::RoleGuest => "ROLE_GUEST",
            Self::RoleAdmin => "ROLE_ADMIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROLE_MEMBER" => Some(Self::RoleMember),
            "ROLE_GUEST" => Some(Self::RoleGuest),
            "ROLE_ADMIN" => Some(Self::RoleAdmin),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct OpenBufferById {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenBufferByPath {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub worktree_id: u64,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpenBufferResponse {
    #[prost(uint64, tag = "1")]
    pub buffer_id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
    #[prost(uint64, optional, tag = "5")]
    pub mtime_seconds: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag = "6")]
    pub mtime_nanos: ::core::option::Option<u32>,
    #[prost(bool, tag = "7")]
    pub is_dirty: bool,
    #[prost(message, repeated, tag = "8")]
    pub diagnostic_sets: ::prost::alloc::vec::Vec<DiagnosticSet>,
    #[prost(message, repeated, tag = "9")]
    pub selections: ::prost::alloc::vec::Vec<Selection>,
    #[prost(string, tag = "10")]
    pub language_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "11")]
    pub completion_triggers: ::prost::alloc::vec::Vec<CompletionTrigger>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBuffer {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(message, repeated, tag = "3")]
    pub operations: ::prost::alloc::vec::Vec<Operation>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Operation {
    #[prost(oneof = "operation::Variant", tags = "1, 2, 3, 4, 5")]
    pub variant: ::core::option::Option<operation::Variant>,
}
/// Nested message and enum types in `Operation`.
pub mod operation {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Edit {
        #[prost(message, optional, tag = "1")]
        pub timestamp: ::core::option::Option<super::LamportTimestamp>,
        #[prost(message, repeated, tag = "2")]
        pub version: ::prost::alloc::vec::Vec<super::VectorClockEntry>,
        #[prost(message, repeated, tag = "3")]
        pub ranges: ::prost::alloc::vec::Vec<super::Range>,
        #[prost(string, repeated, tag = "4")]
        pub new_text: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Undo {
        #[prost(message, optional, tag = "1")]
        pub timestamp: ::core::option::Option<super::LamportTimestamp>,
        #[prost(message, repeated, tag = "2")]
        pub version: ::prost::alloc::vec::Vec<super::VectorClockEntry>,
        #[prost(message, repeated, tag = "3")]
        pub counts: ::prost::alloc::vec::Vec<super::UndoCount>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UpdateSelections {
        #[prost(message, optional, tag = "1")]
        pub timestamp: ::core::option::Option<super::LamportTimestamp>,
        #[prost(message, repeated, tag = "2")]
        pub selections: ::prost::alloc::vec::Vec<super::Selection>,
        #[prost(bool, tag = "3")]
        pub line_mode: bool,
        #[prost(enumeration = "super::CursorShape", tag = "4")]
        pub cursor_shape: i32,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UpdateDiagnostics {
        #[prost(message, optional, tag = "1")]
        pub timestamp: ::core::option::Option<super::LamportTimestamp>,
        #[prost(uint64, tag = "2")]
        pub server_id: u64,
        #[prost(message, repeated, tag = "3")]
        pub diagnostics: ::prost::alloc::vec::Vec<super::Diagnostic>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UpdateCompletionTriggers {
        #[prost(message, optional, tag = "1")]
        pub timestamp: ::core::option::Option<super::LamportTimestamp>,
        #[prost(uint64, tag = "2")]
        pub server_id: u64,
        #[prost(string, repeated, tag = "3")]
        pub triggers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Variant {
        #[prost(message, tag = "1")]
        Edit(Edit),
        #[prost(message, tag = "2")]
        Undo(Undo),
        #[prost(message, tag = "3")]
        UpdateSelections(UpdateSelections),
        #[prost(message, tag = "4")]
        UpdateDiagnostics(UpdateDiagnostics),
        #[prost(message, tag = "5")]
        UpdateCompletionTriggers(UpdateCompletionTriggers),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LamportTimestamp {
    #[prost(uint32, tag = "1")]
    pub replica_id: u32,
    #[prost(uint32, tag = "2")]
    pub value: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct VectorClockEntry {
    #[prost(uint32, tag = "1")]
    pub replica_id: u32,
    #[prost(uint32, tag = "2")]
    pub timestamp: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Anchor {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<LamportTimestamp>,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(enumeration = "Bias", tag = "3")]
    pub bias: i32,
    #[prost(uint32, optional, tag = "4")]
    pub buffer_id: ::core::option::Option<u32>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Range {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<Anchor>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<Anchor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UndoCount {
    #[prost(message, optional, tag = "1")]
    pub operation_timestamp: ::core::option::Option<LamportTimestamp>,
    #[prost(uint32, tag = "2")]
    pub count: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Selection {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<Anchor>,
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<Anchor>,
    #[prost(bool, tag = "4")]
    pub reversed: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Diagnostic {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
    #[prost(enumeration = "Severity", tag = "2")]
    pub severity: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag = "6")]
    pub is_primary: bool,
    #[prost(bool, tag = "7")]
    pub is_disk_based: bool,
    #[prost(uint32, tag = "8")]
    pub group_id: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiagnosticSet {
    #[prost(uint64, tag = "1")]
    pub server_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub diagnostics: ::prost::alloc::vec::Vec<Diagnostic>,
    #[prost(message, optional, tag = "3")]
    pub lamport_timestamp: ::core::option::Option<LamportTimestamp>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionTrigger {
    #[prost(uint64, tag = "1")]
    pub server_id: u64,
    #[prost(string, tag = "2")]
    pub trigger_character: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaveBuffer {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(message, repeated, tag = "3")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BufferSaved {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(message, repeated, tag = "3")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
    #[prost(uint64, tag = "4")]
    pub mtime_seconds: u64,
    #[prost(uint32, tag = "5")]
    pub mtime_nanos: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateBufferFile {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(message, optional, tag = "3")]
    pub file: ::core::option::Option<File>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    #[prost(uint64, tag = "1")]
    pub worktree_id: u64,
    #[prost(uint64, tag = "2")]
    pub entry_id: u64,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub mtime_seconds: u64,
    #[prost(uint32, tag = "5")]
    pub mtime_nanos: u32,
    #[prost(bool, tag = "6")]
    pub is_deleted: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReloadBuffers {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, repeated, tag = "2")]
    pub buffer_ids: ::prost::alloc::vec::Vec<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BufferReloaded {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(message, repeated, tag = "3")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
    #[prost(uint64, tag = "4")]
    pub mtime_seconds: u64,
    #[prost(uint32, tag = "5")]
    pub mtime_nanos: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynchronizeBuffers {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub buffers: ::prost::alloc::vec::Vec<BufferVersion>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynchronizeBuffersResponse {
    #[prost(message, repeated, tag = "1")]
    pub buffers: ::prost::alloc::vec::Vec<BufferVersion>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BufferVersion {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(message, repeated, tag = "2")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Bias {
    Left = 0,
    Right = 1,
}
impl Bias {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Left => "LEFT",
            Self::Right => "RIGHT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LEFT" => Some(Self::Left),
            "RIGHT" => Some(Self::Right),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CursorShape {
    CursorBar = 0,
    CursorBlock = 1,
    CursorUnderline = 2,
    CursorHollow = 3,
}
impl CursorShape {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CursorBar => "CURSOR_BAR",
            Self::CursorBlock => "CURSOR_BLOCK",
            Self::CursorUnderline => "CURSOR_UNDERLINE",
            Self::CursorHollow => "CURSOR_HOLLOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CURSOR_BAR" => Some(Self::CursorBar),
            "CURSOR_BLOCK" => Some(Self::CursorBlock),
            "CURSOR_UNDERLINE" => Some(Self::CursorUnderline),
            "CURSOR_HOLLOW" => Some(Self::CursorHollow),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Error = 0,
    Warning = 1,
    Info = 2,
    Hint = 3,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Error => "SEVERITY_ERROR",
            Self::Warning => "SEVERITY_WARNING",
            Self::Info => "SEVERITY_INFO",
            Self::Hint => "SEVERITY_HINT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_INFO" => Some(Self::Info),
            "SEVERITY_HINT" => Some(Self::Hint),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateParticipantLocation {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(message, optional, tag = "2")]
    pub location: ::core::option::Option<ParticipantLocation>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Follow {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(uint64, optional, tag = "2")]
    pub project_id: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "3")]
    pub leader_id: ::core::option::Option<PeerId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FollowResponse {
    #[prost(message, optional, tag = "1")]
    pub active_view: ::core::option::Option<ViewId>,
    #[prost(message, repeated, tag = "2")]
    pub views: ::prost::alloc::vec::Vec<View>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Unfollow {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(uint64, optional, tag = "2")]
    pub project_id: ::core::option::Option<u64>,
    #[prost(message, optional, tag = "3")]
    pub leader_id: ::core::option::Option<PeerId>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateFollowers {
    #[prost(uint64, tag = "1")]
    pub room_id: u64,
    #[prost(uint64, optional, tag = "2")]
    pub project_id: ::core::option::Option<u64>,
    #[prost(message, repeated, tag = "3")]
    pub follower_ids: ::prost::alloc::vec::Vec<PeerId>,
    #[prost(oneof = "update_followers::Variant", tags = "10, 11, 12")]
    pub variant: ::core::option::Option<update_followers::Variant>,
}
/// Nested message and enum types in `UpdateFollowers`.
pub mod update_followers {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct UpdateActiveView {
        #[prost(message, optional, tag = "1")]
        pub id: ::core::option::Option<super::ViewId>,
        #[prost(message, optional, tag = "2")]
        pub leader_id: ::core::option::Option<super::PeerId>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UpdateView {
        #[prost(message, optional, tag = "1")]
        pub id: ::core::option::Option<super::ViewId>,
        #[prost(message, optional, tag = "2")]
        pub state: ::core::option::Option<super::ViewState>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct CreateView {
        #[prost(message, optional, tag = "1")]
        pub view: ::core::option::Option<super::View>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Variant {
        #[prost(message, tag = "10")]
        UpdateActiveView(UpdateActiveView),
        #[prost(message, tag = "11")]
        UpdateView(UpdateView),
        #[prost(message, tag = "12")]
        CreateView(CreateView),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ViewId {
    #[prost(message, optional, tag = "1")]
    pub creator: ::core::option::Option<PeerId>,
    #[prost(uint64, tag = "2")]
    pub id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct View {
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<ViewId>,
    #[prost(message, optional, tag = "2")]
    pub leader_id: ::core::option::Option<PeerId>,
    #[prost(message, optional, tag = "3")]
    pub state: ::core::option::Option<ViewState>,
    #[prost(string, tag = "4")]
    pub variant: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewState {
    #[prost(bytes = "vec", tag = "1")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LspRequest {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub buffer_id: u64,
    #[prost(uint64, tag = "3")]
    pub language_server_id: u64,
    #[prost(
        oneof = "lsp_request::Request",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21"
    )]
    pub request: ::core::option::Option<lsp_request::Request>,
}
/// Nested message and enum types in `LspRequest`.
pub mod lsp_request {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Request {
        #[prost(message, tag = "10")]
        GetCompletions(super::GetCompletions),
        #[prost(message, tag = "11")]
        GetHover(super::GetHover),
        #[prost(message, tag = "12")]
        GetDefinition(super::GetDefinition),
        #[prost(message, tag = "13")]
        GetReferences(super::GetReferences),
        #[prost(message, tag = "14")]
        GetDocumentSymbols(super::GetDocumentSymbols),
        #[prost(message, tag = "15")]
        PrepareRename(super::PrepareRename),
        #[prost(message, tag = "16")]
        PerformRename(super::PerformRename),
        #[prost(message, tag = "17")]
        GetCodeActions(super::GetCodeActions),
        #[prost(message, tag = "18")]
        ApplyCodeAction(super::ApplyCodeAction),
        #[prost(message, tag = "19")]
        FormatBuffers(super::FormatBuffers),
        #[prost(message, tag = "20")]
        GetSignatureHelp(super::GetSignatureHelp),
        #[prost(message, tag = "21")]
        InlayHints(super::InlayHints),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LspResponse {
    #[prost(
        oneof = "lsp_response::Response",
        tags = "10, 11, 12, 14, 15, 16, 17, 20, 21"
    )]
    pub response: ::core::option::Option<lsp_response::Response>,
}
/// Nested message and enum types in `LspResponse`.
pub mod lsp_response {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "10")]
        Completions(super::Completions),
        #[prost(message, tag = "11")]
        Hover(super::Hover),
        #[prost(message, tag = "12")]
        Locations(super::Locations),
        #[prost(message, tag = "14")]
        DocumentSymbols(super::DocumentSymbols),
        #[prost(message, tag = "15")]
        PrepareRenameResponse(super::PrepareRenameResponse),
        #[prost(message, tag = "16")]
        Transaction(super::Transaction),
        #[prost(message, tag = "17")]
        CodeActions(super::CodeActions),
        #[prost(message, tag = "20")]
        SignatureHelp(super::SignatureHelp),
        #[prost(message, tag = "21")]
        InlayHintsResponse(super::InlayHintsResponse),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCompletions {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
    #[prost(message, repeated, tag = "2")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Completions {
    #[prost(message, repeated, tag = "1")]
    pub completions: ::prost::alloc::vec::Vec<Completion>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Completion {
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub detail: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub old_range: ::core::option::Option<Range>,
    #[prost(string, tag = "4")]
    pub new_text: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub kind: i32,
    #[prost(string, repeated, tag = "6")]
    pub filter_text: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub documentation: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "8")]
    pub server_raw: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetHover {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hover {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
    #[prost(string, repeated, tag = "2")]
    pub contents_markdown: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetDefinition {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetReferences {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
    #[prost(bool, tag = "2")]
    pub include_declaration: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Locations {
    #[prost(message, repeated, tag = "1")]
    pub locations: ::prost::alloc::vec::Vec<Location>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Location {
    #[prost(uint64, tag = "1")]
    pub buffer_id: u64,
    #[prost(message, optional, tag = "2")]
    pub range: ::core::option::Option<Range>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetDocumentSymbols {}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentSymbols {
    #[prost(message, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<DocumentSymbol>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentSymbol {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub kind: i32,
    #[prost(message, optional, tag = "3")]
    pub range: ::core::option::Option<Range>,
    #[prost(message, optional, tag = "4")]
    pub selection_range: ::core::option::Option<Range>,
    #[prost(message, repeated, tag = "5")]
    pub children: ::prost::alloc::vec::Vec<DocumentSymbol>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PrepareRename {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PrepareRenameResponse {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PerformRename {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
    #[prost(string, tag = "2")]
    pub new_name: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCodeActions {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
    #[prost(string, repeated, tag = "2")]
    pub kinds: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeActions {
    #[prost(message, repeated, tag = "1")]
    pub actions: ::prost::alloc::vec::Vec<CodeAction>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CodeAction {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub kind: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub server_raw: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyCodeAction {
    #[prost(message, optional, tag = "1")]
    pub action: ::core::option::Option<CodeAction>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FormatBuffers {
    #[prost(uint64, repeated, tag = "1")]
    pub buffer_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint32, tag = "2")]
    pub trigger: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetSignatureHelp {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignatureHelp {
    #[prost(message, repeated, tag = "1")]
    pub signatures: ::prost::alloc::vec::Vec<Signature>,
    #[prost(uint32, tag = "2")]
    pub active_signature: u32,
    #[prost(uint32, tag = "3")]
    pub active_parameter: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signature {
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub parameters: ::prost::alloc::vec::Vec<Parameter>,
    #[prost(string, tag = "3")]
    pub documentation: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Parameter {
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub documentation: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InlayHints {
    #[prost(message, optional, tag = "1")]
    pub range: ::core::option::Option<Range>,
    #[prost(message, repeated, tag = "2")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InlayHintsResponse {
    #[prost(message, repeated, tag = "1")]
    pub hints: ::prost::alloc::vec::Vec<InlayHint>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InlayHint {
    #[prost(message, optional, tag = "1")]
    pub position: ::core::option::Option<Anchor>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub kind: i32,
    #[prost(bool, tag = "4")]
    pub padding_left: bool,
    #[prost(bool, tag = "5")]
    pub padding_right: bool,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(message, repeated, tag = "1")]
    pub buffer_transactions: ::prost::alloc::vec::Vec<BufferTransaction>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BufferTransaction {
    #[prost(uint64, tag = "1")]
    pub buffer_id: u64,
    #[prost(message, repeated, tag = "2")]
    pub operations: ::prost::alloc::vec::Vec<Operation>,
    #[prost(message, repeated, tag = "3")]
    pub version: ::prost::alloc::vec::Vec<VectorClockEntry>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateDiagnosticSummary {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub worktree_id: u64,
    #[prost(message, optional, tag = "3")]
    pub summary: ::core::option::Option<DiagnosticSummary>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiagnosticSummary {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub language_server_id: u64,
    #[prost(uint32, tag = "3")]
    pub error_count: u32,
    #[prost(uint32, tag = "4")]
    pub warning_count: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateLanguageServer {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub language_server_id: u64,
    #[prost(oneof = "update_language_server::Variant", tags = "3, 4, 5, 6, 7")]
    pub variant: ::core::option::Option<update_language_server::Variant>,
}
/// Nested message and enum types in `UpdateLanguageServer`.
pub mod update_language_server {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct WorkStart {
        #[prost(string, tag = "1")]
        pub token: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "2")]
        pub title: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "3")]
        pub message: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "4")]
        pub percentage: ::core::option::Option<u32>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct WorkProgress {
        #[prost(string, tag = "1")]
        pub token: ::prost::alloc::string::String,
        #[prost(string, optional, tag = "2")]
        pub message: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(uint32, optional, tag = "3")]
        pub percentage: ::core::option::Option<u32>,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct WorkEnd {
        #[prost(string, tag = "1")]
        pub token: ::prost::alloc::string::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct DiskBasedDiagnosticsUpdating {}
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct DiskBasedDiagnosticsUpdated {}
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Variant {
        #[prost(message, tag = "3")]
        WorkStart(WorkStart),
        #[prost(message, tag = "4")]
        WorkProgress(WorkProgress),
        #[prost(message, tag = "5")]
        WorkEnd(WorkEnd),
        #[prost(message, tag = "6")]
        DiskBasedDiagnosticsUpdating(DiskBasedDiagnosticsUpdating),
        #[prost(message, tag = "7")]
        DiskBasedDiagnosticsUpdated(DiskBasedDiagnosticsUpdated),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateRepository {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub repository_id: u64,
    #[prost(string, repeated, tag = "3")]
    pub removed_statuses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub updated_statuses: ::prost::alloc::vec::Vec<StatusEntry>,
    #[prost(message, optional, tag = "5")]
    pub current_branch: ::core::option::Option<Branch>,
    #[prost(string, optional, tag = "6")]
    pub head_commit: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusEntry {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(enumeration = "git_entry::Status", tag = "2")]
    pub status: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Branch {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_head: bool,
    #[prost(uint64, optional, tag = "3")]
    pub upstream_ahead: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "4")]
    pub upstream_behind: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitStage {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub repository_id: u64,
    #[prost(string, repeated, tag = "3")]
    pub paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitUnstage {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub repository_id: u64,
    #[prost(string, repeated, tag = "3")]
    pub paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitCommit {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub repository_id: u64,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub author_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub author_email: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GitBranches {
    #[prost(uint64, tag = "1")]
    pub project_id: u64,
    #[prost(uint64, tag = "2")]
    pub repository_id: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GitBranchesResponse {
    #[prost(message, repeated, tag = "1")]
    pub branches: ::prost::alloc::vec::Vec<Branch>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(uint32, optional, tag = "2")]
    pub responding_to: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "3")]
    pub original_sender_id: ::core::option::Option<PeerId>,
    #[prost(
        oneof = "envelope::Payload",
        tags = "10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 25, 26, 27, 28, 40, 41, 42, 43, 44, 45, 46, 47, 48, 60, 61, 62, 63, 64, 65, 66, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 100, 101, 102, 103, 104, 120, 121, 122, 123, 140, 141, 142, 143, 144, 145"
    )]
    pub payload: ::core::option::Option<envelope::Payload>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        Hello(super::Hello),
        #[prost(message, tag = "11")]
        Ack(super::Ack),
        #[prost(message, tag = "12")]
        Error(super::Error),
        #[prost(message, tag = "13")]
        Ping(super::Ping),
        #[prost(message, tag = "14")]
        Pong(super::Pong),
        #[prost(message, tag = "20")]
        CreateRoom(super::CreateRoom),
        #[prost(message, tag = "21")]
        CreateRoomResponse(super::CreateRoomResponse),
        #[prost(message, tag = "22")]
        JoinRoom(super::JoinRoom),
        #[prost(message, tag = "23")]
        JoinRoomResponse(super::JoinRoomResponse),
        #[prost(message, tag = "24")]
        LeaveRoom(super::LeaveRoom),
        #[prost(message, tag = "25")]
        RoomUpdated(super::RoomUpdated),
        #[prost(message, tag = "26")]
        Call(super::Call),
        #[prost(message, tag = "27")]
        IncomingCall(super::IncomingCall),
        #[prost(message, tag = "28")]
        DeclineCall(super::DeclineCall),
        #[prost(message, tag = "40")]
        ShareProject(super::ShareProject),
        #[prost(message, tag = "41")]
        ShareProjectResponse(super::ShareProjectResponse),
        #[prost(message, tag = "42")]
        UnshareProject(super::UnshareProject),
        #[prost(message, tag = "43")]
        JoinProject(super::JoinProject),
        #[prost(message, tag = "44")]
        JoinProjectResponse(super::JoinProjectResponse),
        #[prost(message, tag = "45")]
        LeaveProject(super::LeaveProject),
        #[prost(message, tag = "46")]
        AddProjectCollaborator(super::AddProjectCollaborator),
        #[prost(message, tag = "47")]
        RemoveProjectCollaborator(super::RemoveProjectCollaborator),
        #[prost(message, tag = "48")]
        UpdateProject(super::UpdateProject),
        #[prost(message, tag = "60")]
        UpdateWorktree(super::UpdateWorktree),
        #[prost(message, tag = "61")]
        CreateProjectEntry(super::CreateProjectEntry),
        #[prost(message, tag = "62")]
        RenameProjectEntry(super::RenameProjectEntry),
        #[prost(message, tag = "63")]
        DeleteProjectEntry(super::DeleteProjectEntry),
        #[prost(message, tag = "64")]
        CopyProjectEntry(super::CopyProjectEntry),
        #[prost(message, tag = "65")]
        ProjectEntryResponse(super::ProjectEntryResponse),
        #[prost(message, tag = "66")]
        ExpandProjectEntry(super::ExpandProjectEntry),
        #[prost(message, tag = "80")]
        OpenBufferById(super::OpenBufferById),
        #[prost(message, tag = "81")]
        OpenBufferByPath(super::OpenBufferByPath),
        #[prost(message, tag = "82")]
        OpenBufferResponse(super::OpenBufferResponse),
        #[prost(message, tag = "83")]
        UpdateBuffer(super::UpdateBuffer),
        #[prost(message, tag = "84")]
        UpdateBufferFile(super::UpdateBufferFile),
        #[prost(message, tag = "85")]
        SaveBuffer(super::SaveBuffer),
        #[prost(message, tag = "86")]
        BufferSaved(super::BufferSaved),
        #[prost(message, tag = "87")]
        ReloadBuffers(super::ReloadBuffers),
        #[prost(message, tag = "88")]
        BufferReloaded(super::BufferReloaded),
        #[prost(message, tag = "89")]
        SynchronizeBuffers(super::SynchronizeBuffers),
        #[prost(message, tag = "90")]
        SynchronizeBuffersResponse(super::SynchronizeBuffersResponse),
        #[prost(message, tag = "100")]
        UpdateParticipantLocation(super::UpdateParticipantLocation),
        #[prost(message, tag = "101")]
        Follow(super::Follow),
        #[prost(message, tag = "102")]
        FollowResponse(super::FollowResponse),
        #[prost(message, tag = "103")]
        Unfollow(super::Unfollow),
        #[prost(message, tag = "104")]
        UpdateFollowers(super::UpdateFollowers),
        #[prost(message, tag = "120")]
        LspRequest(super::LspRequest),
        #[prost(message, tag = "121")]
        LspResponse(super::LspResponse),
        #[prost(message, tag = "122")]
        UpdateDiagnosticSummary(super::UpdateDiagnosticSummary),
        #[prost(message, tag = "123")]
        UpdateLanguageServer(super::UpdateLanguageServer),
        #[prost(message, tag = "140")]
        UpdateRepository(super::UpdateRepository),
        #[prost(message, tag = "141")]
        GitStage(super::GitStage),
        #[prost(message, tag = "142")]
        GitUnstage(super::GitUnstage),
        #[prost(message, tag = "143")]
        GitCommit(super::GitCommit),
        #[prost(message, tag = "144")]
        GitBranches(super::GitBranches),
        #[prost(message, tag = "145")]
        GitBranchesResponse(super::GitBranchesResponse),
    }
}
