#!/usr/bin/env bash
set -euo pipefail

# Regenerate src/generated.rs and src/generated_collab.rs from .proto definitions.
# Requires `protoc` to be available on PATH (prost-build invokes it internally).

RAIDIAN_DIR="$(cd "$(dirname "$0")" && pwd)"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

cat > "$TMP_DIR/Cargo.toml" <<'EOF'
[package]
name = "proto-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
prost-build = "0.13"
EOF

cat > "$TMP_DIR/main.rs" <<'EOF'
fn main() {
    // Business API (package `raidian` and `raidian.proto`).
    let mut config = prost_build::Config::new();
    config
        .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
        .out_dir("src")
        .compile_protos(
            &[
                "proto/auth.proto",
                "proto/repository.proto",
                "proto/issue.proto",
                "proto/merge_request.proto",
                "proto/pipeline.proto",
                "proto/member.proto",
                "proto/collaboration.proto",
                "proto/dashboard.proto",
            ],
            &["proto"],
        )
        .expect("prost-build (business) failed");
    std::fs::rename("src/raidian.rs", "src/generated.rs")
        .expect("failed to rename generated business file");
    // The business set also produces the `raidian.proto` (pipeline) submodule;
    // merge it in-place so downstream only sees one file.
    if std::path::Path::new("src/raidian.proto.rs").exists() {
        let pipeline = std::fs::read_to_string("src/raidian.proto.rs")
            .expect("read raidian.proto.rs");
        let mut merged = std::fs::read_to_string("src/generated.rs")
            .expect("read generated.rs");
        merged.push_str("\npub mod pipeline_proto {\n");
        merged.push_str(&pipeline);
        merged.push_str("}\n");
        std::fs::write("src/generated.rs", merged).expect("write merged generated.rs");
        std::fs::remove_file("src/raidian.proto.rs").ok();
    }

    // Zed-style collab protos (package `raidian.collab`).
    let mut collab = prost_build::Config::new();
    collab
        .type_attribute(".", "#[derive(serde::Serialize, serde::Deserialize)]")
        .out_dir("src")
        .compile_protos(
            &[
                "proto/peer.proto",
                "proto/envelope.proto",
                "proto/session.proto",
                "proto/room.proto",
                "proto/project.proto",
                "proto/worktree.proto",
                "proto/buffer.proto",
                "proto/collaborator.proto",
                "proto/lsp.proto",
                "proto/git.proto",
            ],
            &["proto"],
        )
        .expect("prost-build (collab) failed");
    std::fs::rename("src/raidian.collab.rs", "src/generated_collab.rs")
        .expect("failed to rename generated collab file");
    println!("Generated src/generated.rs and src/generated_collab.rs successfully");
}
EOF

mkdir -p "$TMP_DIR/src"
cp "$TMP_DIR/main.rs" "$TMP_DIR/src/main.rs"
cp -r proto "$TMP_DIR/"

cd "$TMP_DIR"
cargo run --quiet

HEADER='// Auto-generated by prost-build. DO NOT EDIT MANUALLY.
//
// Source of truth: crates/raidian/proto/*.proto
// Regenerate with: bash crates/raidian/generate.sh
//
// This file is intentionally committed so that downstream consumers
// (CLI, Zed, Logos, etc.) do not need `protoc` installed.
'

printf "%s\n" "$HEADER" | cat - "$TMP_DIR/src/generated.rs" > "$RAIDIAN_DIR/src/generated.rs"
printf "%s\n" "$HEADER" | cat - "$TMP_DIR/src/generated_collab.rs" > "$RAIDIAN_DIR/src/generated_collab.rs"
echo "crates/raidian/src/generated.rs and generated_collab.rs updated."
